# Generated by Django 5.2.10 on 2026-01-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade_value',
            new_name='grade_number',
        ),
    ]
