# Generated by Django 5.2.10 on 2026-01-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_grade_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade_letter',
        ),
    ]
